/***********************************
 * 기업 대출잔액 추이 - 기업대출 추이(전체) (보고서 p.1, [그림1])
 * RFP p.11 [그림1] 기업대출 추이(전체)
 * 활용 테이블 : BASIC_BIZ_LOAN
 ***********************************/
DROP TABLE IF EXISTS RESULT_BIZLOANTREND_TOTAL;
SELECT DISTINCT
	t00.GG_YM,
	t00.IND_BIZ_LOAN,
	t00.CORP_BIZ_LOAN,
	t00.IND_BIZ_LOAN + t00.CORP_BIZ_LOAN as "TOT_BIZ_LOAN"
	INTO RESULT_BIZLOANTREND_TOTAL
FROM
	(
	SELECT
		t0.GG_YM,
		ROUND(SUM(CASE WHEN t0.BRWR_NO_TP_CD = 1 THEN t0.BIZ_LOAN ELSE 0 END) OVER(PARTITION BY t0.GG_YM), 0) as "IND_BIZ_LOAN",
		ROUND(SUM(CASE WHEN t0.BRWR_NO_TP_CD = 3 THEN t0.BIZ_LOAN ELSE 0 END) OVER(PARTITION BY t0.GG_YM), 0) as "CORP_BIZ_LOAN"
	FROM
		(
		SELECT DISTINCT 
			t.GG_YM, 
			t.BRWR_NO_TP_CD, 
			SUM(t.BRNO_AMT) OVER(PARTITION BY t.GG_YM, t.BRWR_NO_TP_CD) as "BIZ_LOAN"	-- 사업자 대출
		FROM
			BASIC_BIZ_LOAN t
		WHERE
			t.GG_YM <= TO_CHAR(SYSDATE, 'YYYYMM')
		    AND NVL(t.EFAS, '') <> '55'	-- 금융보험업 제외
		) t0
	) t00
ORDER BY
	t00.GG_YM;
-- 결과조회
SELECT * FROM RESULT_BIZLOANTREND_TOTAL ORDER BY GG_YM;