/******************************************
 * 기업 대출잔액 추이 - 기업규모별 대출(대/중견/중소) (보고서 p.1, [그림2])
 * RFP p.11 [그림2] 기업규모별 대출(대/중견/중소)
 * 활용 테이블 : BASIC_BIZ_LOAN
 ******************************************/
DROP TABLE IF EXISTS RESULT_BIZLOANTREND_BIZSIZE;
SELECT DISTINCT 
	t000.GG_YM, 
	ROUND(SUM(t000.BRNO_AMT_1) OVER(PARTITION BY t000.GG_YM), 0) as LOAN_BIZ_SIZE_1,
	ROUND(SUM(t000.BRNO_AMT_2) OVER(PARTITION BY t000.GG_YM), 0) as LOAN_BIZ_SIZE_2,
	ROUND(SUM(t000.BRNO_AMT_3) OVER(PARTITION BY t000.GG_YM), 0) as LOAN_BIZ_SIZE_3,
	ROUND(SUM(t000.BRNO_AMT_0) OVER(PARTITION BY t000.GG_YM), 0) as LOAN_BIZ_SIZE_0
	INTO RESULT_BIZLOANTREND_BIZSIZE
FROM 
	(
	SELECT   	
	  	t00.*,
	  	DECODE(t00.BIZ_SIZE, '1', t00.BRNO_AMT, 0) as BRNO_AMT_1,	-- 대기업
	  	DECODE(t00.BIZ_SIZE, '2', t00.BRNO_AMT, 0) as BRNO_AMT_2,	-- 중소기업
	  	DECODE(t00.BIZ_SIZE, '3', t00.BRNO_AMT, 0) as BRNO_AMT_3,	-- 중견기업
	  	DECODE(t00.BIZ_SIZE, '0', t00.BRNO_AMT, DECODE(t00.BIZ_SIZE, NULL, t00.BRNO_AMT, 0)) as BRNO_AMT_0	-- 기타
	FROM
		(
		SELECT
			t0.GG_YM,
			t0.BRWR_NO_TP_CD,
			t0.CORP_NO,
			t0.BRNO,
			t0.SOI_CD,
			t0.EI_ITT_CD,
			t0.BR_ACT,
			t0.BRNO_AMT,
			t0.KSIC,
			t0.EFAS,
			DECODE(t0.BRWR_NO_TP_CD, '1', '2', t0.BIZ_SIZE) as BIZ_SIZE,
			t0.OSIDE_ISPT_YN,
			t0.BLIST_MRKT_DIVN_CD,
			t0.CORP_CRI,
			t0.SOI_CD2
		FROM 
			BASIC_BIZ_LOAN t0
		) t00
	) t000	
WHERE
	t000.GG_YM <= TO_CHAR(SYSDATE, 'YYYYMM')
	AND NVL(t000.EFAS, '') <> '55'	-- 금융보험업 제외
ORDER BY 
  	t000.GG_YM;


  
  
  
 /******************************************
 * 기업 대출잔액 추이 - 신용등급별 (법인 중소기업에 한함) (p.1, [그림2])
 * 활용 테이블 : BASIC_BIZ_LOAN
 ******************************************/
DROP TABLE IF EXISTS RESULT_BIZLOANTREND_BIZCREDIT_CORP;
SELECT DISTINCT
	t000.GG_YM,
  	ROUND(SUM(t000.BRNO_AMT_CRI1) OVER(PARTITION BY t000.GG_YM), 0) as LOAN_CRI1,
  	ROUND(SUM(t000.BRNO_AMT_CRI2) OVER(PARTITION BY t000.GG_YM), 0) as LOAN_CRI2,
  	ROUND(SUM(t000.BRNO_AMT_CRI3) OVER(PARTITION BY t000.GG_YM), 0) as LOAN_CRI3,
  	ROUND(SUM(t000.BRNO_AMT_CRI4) OVER(PARTITION BY t000.GG_YM), 0) as LOAN_CRI4
  	INTO RESULT_BIZLOANTREND_BIZCREDIT_CORP
FROM
	(
	SELECT 
		t00.*,
		DECODE(t00.BIZ_CRI, '1. 투기(BB+이하 C이상)', t00.BRNO_AMT, 0) as BRNO_AMT_CRI1,	-- 투기(BB+이하 C이상)
		DECODE(t00.BIZ_CRI, '2. 투자(BBB-이상)', t00.BRNO_AMT, 0) as BRNO_AMT_CRI2,	-- 투자(BBB-이상)
		DECODE(t00.BIZ_CRI, '3. 상환불능(D이하)', t00.BRNO_AMT, 0) as BRNO_AMT_CRI3,	-- 상환불능(D이하)
		DECODE(t00.BIZ_CRI, '4. 신용등급 미부여', t00.BRNO_AMT, 0) as BRNO_AMT_CRI4	-- 신용등급 미부여 등
	FROM
		(
		SELECT
			t0.*, 
			CASE 
		  		WHEN (t0.CORP_CRI >= 4 AND t0.CORP_CRI <= 14) THEN '1. 투기(BB+이하 C이상)'
		  		WHEN t0.CORP_CRI >= 15 THEN '2. 투자(BBB-이상)'
		  		WHEN (t0.CORP_CRI >= 2 AND t0.CORP_CRI <= 3) THEN '3. 상환불능(D이하)'
		  		ELSE '4. 신용등급 미부여'
		  	END as BIZ_CRI
		FROM 
		  	BASIC_BIZ_LOAN t0 
		WHERE
			t0.GG_YM <= TO_CHAR(SYSDATE, 'YYYYMM')
			AND NVL(t0.EFAS, '') <> '55'	-- 금융보험업 제외
			AND t0.BRWR_NO_TP_CD = '3'	-- 법인만
			AND t0.BIZ_SIZE = 2 -- 중소기업만
		ORDER BY 
		  	t0.GG_YM
		) t00
	) t000
ORDER BY t000.GG_YM;





/******************************************
 * 기업 대출잔액 추이 - 신용등급별 (개인기업에 한함) (p.1, [그림2])
 * 활용 테이블 : BASIC_BIZ_LOAN
 ******************************************/
DROP TABLE IF EXISTS RESULT_BIZLOANTREND_BIZCREDIT_INDBIZ;
SELECT DISTINCT
	t00.GG_YM,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD1) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD1,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD2) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD2,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD3) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD3,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD4) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD4,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD5) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD5,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD6) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD6,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD7) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD7,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD8) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD8,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD9) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD9,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD10) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD10,
  	ROUND(SUM(t00.BRNO_AMT_SCRGRAD99) OVER(PARTITION BY t00.GG_YM), 0) as LOAN_SCRGRAD99
  	INTO RESULT_BIZLOANTREND_BIZCREDIT_INDBIZ
FROM
	(
	SELECT
		t0.*, 
		DECODE(t0.CORP_CRI, 1, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD1,	-- SCR_CRAD_1
		DECODE(t0.CORP_CRI, 2, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD2,	-- SCR_CRAD_2
		DECODE(t0.CORP_CRI, 3, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD3,	-- SCR_CRAD_3
		DECODE(t0.CORP_CRI, 4, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD4,	-- SCR_CRAD_4
		DECODE(t0.CORP_CRI, 5, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD5,	-- SCR_CRAD_5
		DECODE(t0.CORP_CRI, 6, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD6,	-- SCR_CRAD_6
		DECODE(t0.CORP_CRI, 7, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD7,	-- SCR_CRAD_7
		DECODE(t0.CORP_CRI, 8, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD8,	-- SCR_CRAD_8
		DECODE(t0.CORP_CRI, 9, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD9,	-- SCR_CRAD_9
		DECODE(t0.CORP_CRI, 10, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD10,	-- SCR_CRAD_10
		DECODE(NVL(t0.CORP_CRI, 0), 0, t0.BRNO_AMT, 0) as BRNO_AMT_SCRGRAD99	-- SCR_CRAD_99
	FROM 
	  	BASIC_BIZ_LOAN t0 
	WHERE
		t0.GG_YM <= TO_CHAR(SYSDATE, 'YYYYMM')
		AND NVL(t0.EFAS, '') <> '55'	-- 금융보험업 제외
		AND t0.BRWR_NO_TP_CD = '1'	-- 개인만`
	ORDER BY 
	  	t0.GG_YM
	) t00
ORDER BY t00.GG_YM;





-- 결과 조회 : 월별 기업규모별 대출
SELECT * FROM RESULT_BIZLOANTREND_BIZSIZE ORDER BY GG_YM;
-- 결과 조회 : 신용등급별 대출(법인, 중소기업)
SELECT * FROM RESULT_BIZLOANTREND_BIZCREDIT_CORP ORDER BY GG_YM;
-- 결과 조회 : 신용등급별 대출(개인, 중소기업)
SELECT * FROM RESULT_BIZLOANTREND_BIZCREDIT_INDBIZ ORDER BY GG_YM;
